export const GET_EMPLOYEE_DATA_REQUEST = "GET_EMPLOYEE_DATA_REQUEST";
export const GET_EMPLOYEE_DATA_SUCCESS = "GET_EMPLOYEE_DATA_SUCCESS";
export const GET_EMPLOYEE_DATA_FAILURE = "GET_EMPLOYEE_DATA_FAILURE";

export const ADD_EMPLOYEE_DATA_REQUEST = "ADD_EMPLOYEE_DATA_REQUEST";
export const ADD_EMPLOYEE_DATA_SUCCESS = "ADD_EMPLOYEE_DATA_SUCCESS";
export const ADD_EMPLOYEE_DATA_FAILURE = "ADD_EMPLOYEE_DATA_FAILURE";


export const EDIT_EMPLOYEE_DATA_REQUEST = "EDIT_EMPLOYEE_DATA_REQUEST";
export const EDIT_EMPLOYEE_DATA_SUCCESS = "EDIT_EMPLOYEE_DATA_SUCCESS";
export const EDIT_EMPLOYEE_DATA_FAILURE = "EDIT_EMPLOYEE_DATA_FAILURE";